version: "3.9"

services:
    app:
        container_name: aa-nginx
        image: aa-nginx
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "80:80"
